import {
  HOME_SCREEN,
  SEARCH_MUSIC_SCREEN,
  DEMO_SCREEN,
  CATCHER_SCREEN,
  MEDIA_PLAYER_SCREEN,
} from './routes';

export {
  HOME_SCREEN,
  SEARCH_MUSIC_SCREEN,
  DEMO_SCREEN,
  CATCHER_SCREEN,
  MEDIA_PLAYER_SCREEN,
};
